# Generated by Django 6.0.5 on 2026-05-24 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HOTEL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('image', models.ImageField(upload_to='app/')),
                ('link', models.URLField()),
            ],
        ),
        migrations.DeleteModel(
            name='post',
        ),
        migrations.DeleteModel(
            name='seller',
        ),
    ]
