# Generated by Django 6.0.5 on 2026-05-24 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_hotel_delete_post_delete_seller'),
    ]

    operations = [
        migrations.CreateModel(
            name='fam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='app/')),
            ],
        ),
    ]
