# Generated by Django 6.0.5 on 2026-05-25 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_fam'),
    ]

    operations = [
        migrations.CreateModel(
            name='ruk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='app/')),
            ],
        ),
    ]
